INSERT {
	GRAPH <http://sid-unizar-search.com/importance/facts> {
		?uri a <http://sid-unizar-search.com/importance/Predicate> .
		?uri <http://sid-unizar-search.com/importance/typeFrequencyP> ?typeCount .
	}
}
WHERE {
	SELECT ?uri (count(distinct ?class) as ?typeCount) 
    WHERE {
		?s a ?class .
    	?s ?uri ?o .
  	}
    GROUP by ?uri 
}


# SELECT * {
# 	GRAPH <http://sid-unizar-search.com/importance/facts> {
#		?factURI a <http://sid-unizar-search.com/importance/Predicate>. 
#		?factURI <http://sid-unizar-search.com/importance/typeFrequencyP> ?c . 
#	}
#}