PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX math: <http://www.w3.org/2005/xpath-functions/math#>

INSERT {
	GRAPH <http://sid-unizar-search.com/importance/facts> {
		?propTypeElem a <http://sid-unizar-search.com/importance/Predicate-Type> .
		?propTypeElem <http://sid-unizar-search.com/importance/entityTypeImportance> ?entityImp .
	}
}
WHERE {
	
	SELECT ?propTypeElem ?entityImp 
	WHERE {
		
		## We get for each class and property, their EF_pt and the TF_p 
		GRAPH <http://sid-unizar-search.com/importance/facts> {
			?propTypeElem a <http://sid-unizar-search.com/importance/Predicate-Type> . 
			?propTypeElem <http://sid-unizar-search.com/importance/entityFrequencyType> ?ef_pt. 
			?propTypeElem <http://sid-unizar-search.com/importance/predicate> ?uri . 
			?propTypeElem <http://sid-unizar-search.com/importance/type> ?class . 
		}
		
		## This subquery calculates the number of entities in a type in the KB
		{ 
			SELECT (count (distinct ?s) as ?numEntities) 
			WHERE {
				?s a ?class. 
			}
		}
		
		BIND (IF(?ef_pt = 0, xsd:double(0), 
      xsd:double(?ef_pt) * math:log ( xsd:double(?numEntities) / xsd:double(?ef_pt))) as ?entityImp)
		
		
	
	}
}


# SELECT * {
# 	GRAPH <http://sid-unizar-search.com/importance/facts> {
#		?factURI a <http://sid-unizar-search.com/importance/Predicate-Type>. 
#		?factURI <http://sid-unizar-search.com/importance/entityTypeImportance> ?c . 
#	}
#}