PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX math: <http://www.w3.org/2005/xpath-functions/math#>

INSERT {
	GRAPH <http://sid-unizar-search.com/importance/facts> {
		?predTypeURI a <http://sid-unizar-search.com/importance/Predicate-Type> .
		?predTypeURI <http://sid-unizar-search.com/importance/entropyTypeImportance> ?entType
	}
}
WHERE {
	
	SELECT  ?predTypeURI ( (?imp * ?ent) as ?entType)
	{
		GRAPH <http://sid-unizar-search.com/importance/facts> {
			?predTypeURI a <http://sid-unizar-search.com/importance/Predicate-Type>. 
			?predTypeURI <http://sid-unizar-search.com/importance/typeImportance> ?imp. 		
			?predTypeURI <http://sid-unizar-search.com/importance/predicateEntropyType> ?ent. 
		}
	}
}

# SELECT * {
# 	GRAPH <http://sid-unizar-search.com/importance/facts> {
#		?factURI a <http://sid-unizar-search.com/importance/Predicate-Type>. 
#		?factURI <http://sid-unizar-search.com/importance/entropyTypeImportance> ?c . 
#	}
#}
