SELECT ?pred ?type ?predicateEntropyType
WHERE { 
        ?factURI a <http://sid-unizar-search.com/importance/Predicate-Type>.
        ?factURI <http://sid-unizar-search.com/importance/predicate> ?pred .
        ?factURI <http://sid-unizar-search.com/importance/type> ?type .

        ?factURI <http://sid-unizar-search.com/importance/predicateEntropyType> ?predicateEntropyType .
}
